[project]
drom-version = "0.1"

[project]
authors = ["David Declerck <david.declerck@ocamlpro.com>",
           "Steven De Oliveira <steven.de-oliveira@ocamlpro.com>" ]
bug-reports = "https://github.com/OCamlPro/ocaml-solidity/issues"
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro & Origin Labs"
dev-repo = "git+https://github.com/OcamlPro/ocaml-solidity"
edition = "4.10.0"
github-organization = "OCamlPro"
homepage = "https://github.com/OcamlPro/ocaml-solidity"
license = "LGPL2"
min-edition = "4.08.0"
name = "ocaml-solidity"
synopsis = "The ocaml-solidity project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."

[project]
description = """\nOcaml-solidity provides a Solidity parser and typechecker
"""

[project]
skip = "src/ez-hash/index.mld src/ez-hash/ez-hash_stubs.c src/ez-hash/main.ml src/ocaml-solidity-common/main.ml src/ocaml-solidity-parser/main.ml src/ocaml-solidity-checker/main.ml src/ocaml-solidity-test/main.ml src/ocaml-solidity-alcotest/main.ml"

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/ocaml-solidity"
# edit 'src/ocaml-solidity/package.toml' for package-specific options

[[package]]
dir = "src/ez-hash"
# edit 'src/ez-hash/package.toml' for package-specific options

[[package]]
dir = "src/ocaml-solidity-common"
# edit 'src/ocaml-solidity-common/package.toml' for package-specific options

[[package]]
dir = "src/ocaml-solidity-parser"
# edit 'src/ocaml-solidity-parser/package.toml' for package-specific options

[[package]]
dir = "src/ocaml-solidity-checker"
# edit 'src/ocaml-solidity-checker/package.toml' for package-specific options

[[package]]
dir = "src/ocaml-solidity-test"
# edit 'src/ocaml-solidity-test/package.toml' for package-specific options

[[package]]
dir = "src/ocaml-solidity-alcotest"
# edit 'src/ocaml-solidity-test/package.toml' for package-specific options
